# Generated by Django 4.0.3 on 2022-04-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_investor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
