# Generated by Django 4.0.3 on 2022-04-02 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_progress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Progress',
            new_name='Progress_Block',
        ),
    ]
