# Generated by Django 4.0.3 on 2022-04-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_progress_progress_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress_block',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
