# Generated by Django 4.0.3 on 2022-04-02 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_progress_block_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
