# Generated by Django 4.0.3 on 2022-04-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unfair_advantage', models.CharField(max_length=1000)),
                ('target_audience', models.CharField(max_length=200)),
                ('num_of_customers', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
