# Generated by Django 4.0.3 on 2022-04-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_delete_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='problem_statemant',
            field=models.CharField(default='temp', max_length=1000),
            preserve_default=False,
        ),
    ]
