# Generated by Django 4.0.3 on 2022-04-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_progress_block_high_level_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoping_Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
