# Generated by Django 4.0.3 on 2022-04-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_scoping_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoping_block',
            name='phase_name',
            field=models.CharField(max_length=1000),
        ),
    ]
