# Generated by Django 4.0.3 on 2022-04-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_scoping_block_phase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoping_block',
            name='phase_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
