# Generated by Django 4.0.3 on 2022-04-04 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_scoping_block_progress_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoping_block',
            name='progress_block',
        ),
        migrations.AddField(
            model_name='progress_block',
            name='scoping_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.scoping_block'),
        ),
    ]
