# Generated by Django 4.0.3 on 2022-04-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_remove_scoping_block_progress_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoping_block',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
