# Generated by Django 4.0.3 on 2022-04-09 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_scoping_block_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='High_Level_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.scoping_block')),
            ],
        ),
    ]
