# Generated by Django 4.0.3 on 2022-04-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_progress_block_high_level_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress_block',
            name='High_Level_Task',
        ),
    ]
