# Generated by Django 4.0.3 on 2022-04-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_alter_progress_block_high_level_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress_block',
            name='high_level_task',
            field=models.ForeignKey(blank=True, limit_choices_to={'scope.phase_name': models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.scoping_block')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.high_level_task'),
        ),
    ]
