# Generated by Django 4.0.3 on 2022-04-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_progress_block_high_level_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress_block',
            name='high_level_purpose',
        ),
    ]
