# Generated by Django 4.0.3 on 2022-04-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_high_level_task_project_progress_block_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoping_block',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
    ]
